# Generated by Django 5.1.8 on 2025-04-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pihome', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mqttbutton',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
